[project]
name = "fizzbuzz-tdd-kata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Uzair017", email = "uzairrafiq2627@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []



[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "marimo>=0.24.2",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.8",
]

#this is what i added later on 25/9/26
[tool.pytest.ini_options]
pythonpath=["src"]
testpaths=["tests"]
